[files]
extend-exclude = ["target/", ".git/"]

[default]
extend-ignore-re = [
  # snarkVM types that look like typos
  "Credits",
  "credits",
  "TestnetV3",
  "Beacon",
  "BeaconPrivateKey",
]

[default.extend-words]
aleo = "aleo"
serde = "serde"
snarkvm = "snarkvm"
synthesizer = "synthesizer"
