# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
  #"x86_64-unknown-linux-musl",
]
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
  #"RUSTSEC-0000-0000",
]
#git-fetch-with-cli = true

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-3.0"]
confidence-threshold = 0.8
exceptions = [
  #{ allow = ["Zlib"], crate = "adler32" },
]
[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
[sources.allow-org]
github = []
gitlab = []
bitbucket = []
