[package]
name = "aleo-network"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
snarkvm.workspace = true
tokio.workspace = true
tracing.workspace = true

[lib]
name = "aleo_network"
path = "src/lib.rs"
